### ISSUE TITLE
Consider returning the raw map

### ISSUE THREAD

**Issue by igorhub** [midir99/sqload#8]
I see the value of loading queries into a typed struct, but the need to keep it in sync with .sql files can be annoying at times, especially in the early stages of development when everything is in flux.

Consider the option of simply returning the map that we get from `extractQueries`.

**Comment by midir99** [comment]
Hey, hope you are doing well!

Sorry for the late response, I'm considering the option to simply return the map created by `extractQueries`, currently the only reason I would not like to do this is because there would be more than 1 way to get the queries (using structs or maps) and when I created this library I tried to stick to the philosophy of Go of having 1 single obvious way to do a task.

I can probably make this change in the next week..

**Comment by igorhub** [comment]
Perhaps, the loading functions can return the map, and typing can be provided a la carte? We could call it like this:

```
var q = sqload.MustLoadFromFile("sql/users.sql").IntoStruct[struct {
	FindUserById        string `query:"FindUserById"`
	UpdateFirstNameById string `query:"UpdateFirstNameById"`
	DeleteUserById      string `query:"DeleteUserById"`
}]()
```
The least invasive, non-breaking alternative is to provide the map inside the structure itself. Something like that:

```
var q = sqload.MustLoadFromFile[struct {
	FindUserById        string            `query:"FindUserById"`
	UpdateFirstNameById string            `query:"UpdateFirstNameById"`
	DeleteUserById      string            `query:"DeleteUserById"`
	dbg                 map[string]string `allQueries:""`
}]("sql/users.sql")
```
It may look hacky, but it’s for tinkering anyway.

**Comment by midir99** [comment]
Probably the least non-breaking alternative is just my making `extractQueries` public my friend... I'll start working on this using this approach sooner, feel free to open any PR if you want to implement this change, thank you!

**Comment by igorhub** [comment]
I played with both approaches and I like #10 better. It doesn't seem to break anything.

**Comment by midir99** [comment]
Hey @igorhub !

Sorry for taking so long to reply, I've been stuck at job!

It's done!

https://pkg.go.dev/github.com/midir99/sqload@v1.1.0#ExtractQueryMap

Thank you so much for your feedback here.
